--Inserting all records of the final four contestants of Survivor into the table
INSERT INTO Final_Four(Season, Season_Theme, Last_Name, First_Name, Gender, Age, Win_Final_Four, Participate_in_Fire, Win_Fire, Final_Three, Win_Season, Votes_to_Win)
VALUES 
  (35, 'Heroes vs Healers vs Hustlers', 'Pinto', 'Devon', 'M', 23, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (35, 'Heroes vs Healers vs Hustlers', 'Ulrich', 'Ryan', 'M', 23, 'No', 'No', NULL, 'Yes', 'No', 1)
, (35, 'Heroes vs Healers vs Hustlers', 'Hofbeck', 'Chrissy', 'F', 46, 'Yes', 'No', NULL, 'Yes', 'No', 2)
, (35, 'Heroes vs Healers vs Hustlers', 'Driebergen', 'Ben', 'M', 34, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 5)
, (36, 'Ghost Island', 'Perkins', 'Angela', 'F', 42, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (36, 'Ghost Island', 'Johnson', 'Laurel', 'F', 29, 'No', 'No', NULL, 'Yes', 'No', 0)
, (36, 'Ghost Island', 'Abbate', 'Domenick', 'M', 38, 'Yes', 'No', NULL, 'Yes', 'No', 5)
, (36, 'Ghost Island', 'Hollands', 'Wendell', 'M', 33, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 6)
, (37, 'David vs Goliath', 'Kay', 'Kara', 'F', 30, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (37, 'David vs Goliath', 'Keeley', 'Angelina', 'F', 28, 'No', 'No', NULL, 'Yes', 'No', 0)
, (37, 'David vs Goliath', 'White', 'Mike', 'M', 47, 'No', 'Yes', 'Yes', 'Yes', 'No', 3)
, (37, 'David vs Goliath', 'Wilson', 'Nick', 'M', '27', 'Yes', 'No', NULL, 'Yes', 'Yes', 7)
, (38, 'Edge of Extinction', 'Devens', 'Rick', 'M', 33, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (38, 'Edge of Extinction', 'Rosenberg', 'Julie', 'F', 46, 'No', 'No', NULL, 'Yes', 'No', 0)
, (38, 'Edge of Extinction', 'Whitson', 'Gavin', 'M', 23, 'No', 'No', NULL, 'Yes', 'No', 4)
, (38, 'Edge of Extinction', 'Underwood', 'Chris', 'M', 25, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 9)
, (39, 'Island of the Idols', 'Beck', 'Lauren', 'F', 28, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (39, 'Island of the Idols', 'Salman', 'Noura', 'F', 36, 'Yes', 'No', NULL, 'Yes', 'No', 0)
, (39, 'Island of the Idols', 'Kowalski', 'Dean', 'M', 29, 'No', 'Yes', 'Yes', 'Yes', 'No', 2)
, (39, 'Island of the Idols', 'Sheehan', 'Tommy', 'M', 26, 'No', 'No', NULL, 'Yes', 'Yes', 8)
, (40, 'Winners at War', 'Lacina', 'Sarah', 'F', 34, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (40, 'Winners at War', 'Fitzgerald', 'Michele', 'F', 29, 'No', 'No', NULL, 'Yes', 'No', 0)
, (40, 'Winners at War', 'Anderson', 'Natalie', 'F', 33, 'Yes', 'No', NULL, 'Yes', 'No', 4)
, (40, 'Winners at War', 'Vlachos', 'Tony', 'M', 45, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 12)
, (41, '41', 'Aldret', 'Heather', 'F', 52, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (41, '41', 'Hastings', 'Xander', 'M', 21, 'Yes', 'No', NULL, 'Yes', 'No', 0)
, (41, '41', 'Radden', 'Deshawn', 'M', 26, 'No', 'Yes', 'Yes', 'Yes', 'No', 1)
, (41, '41', 'Casupanan', 'Erika', 'F', 31, 'No', 'No', NULL, 'Yes', 'Yes', 7)
, (42, '42', 'Young', 'Jonathan', 'M', 29, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (42, '42', 'Escobar', 'Romeo', 'M', 37, 'Yes', 'No', NULL, 'Yes', 'No', 0)
, (42, '42', 'Turner', 'Mike', 'M', 58, 'No', 'Yes', 'Yes', 'Yes', 'No', 1)
, (42, '42', 'Oketch', 'Maryanne', 'F', 24, 'No', 'No', NULL, 'Yes', 'Yes', 7)
, (43, '43', 'Lopez', 'Jesse', 'M', 30, 'No', 'Yes', 'No', 'No', 'No', NULL)
, (43, '43', 'Knight', 'Owen', 'M', 30, 'No', 'No', NULL, 'Yes', 'No', 0)
, (43, '43', 'Clark', 'Cassidy', 'F', 26, 'Yes', 'No', NULL, 'Yes', 'No', 1)
, (43, '43', 'Gabler', 'Mike', 'M', 51, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 7)